modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="drawer"
version="0.1.9"
displayName="Drawer"
credits="Credit to Aesterial-Arts for the open sounds - https://freesound.org/people/Aesterial-Arts/. Created using mod maker MCreator - https://mcreator.net/about. Credit to Fabric Generator for MCreator by Goldorion"
displayURL="https://entzomc.com/mods"
logoFile="logo.png"
authors="Entzo"
description="Adds drawers to the game"

[[dependencies.drawer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




